// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: questionprotoG.proto

package questionPbgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuestionGrpcClient is the client API for QuestionGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuestionGrpcClient interface {
	GetQuestions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuestionResponse, error)
}

type questionGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionGrpcClient(cc grpc.ClientConnInterface) QuestionGrpcClient {
	return &questionGrpcClient{cc}
}

func (c *questionGrpcClient) GetQuestions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuestionResponse, error) {
	out := new(QuestionResponse)
	err := c.cc.Invoke(ctx, "/questionprotoG.QuestionGrpc/GetQuestions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionGrpcServer is the server API for QuestionGrpc service.
// All implementations must embed UnimplementedQuestionGrpcServer
// for forward compatibility
type QuestionGrpcServer interface {
	GetQuestions(context.Context, *Empty) (*QuestionResponse, error)
	mustEmbedUnimplementedQuestionGrpcServer()
}

// UnimplementedQuestionGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedQuestionGrpcServer struct {
}

func (UnimplementedQuestionGrpcServer) GetQuestions(context.Context, *Empty) (*QuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestions not implemented")
}
func (UnimplementedQuestionGrpcServer) mustEmbedUnimplementedQuestionGrpcServer() {}

// UnsafeQuestionGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestionGrpcServer will
// result in compilation errors.
type UnsafeQuestionGrpcServer interface {
	mustEmbedUnimplementedQuestionGrpcServer()
}

func RegisterQuestionGrpcServer(s grpc.ServiceRegistrar, srv QuestionGrpcServer) {
	s.RegisterService(&QuestionGrpc_ServiceDesc, srv)
}

func _QuestionGrpc_GetQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionGrpcServer).GetQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/questionprotoG.QuestionGrpc/GetQuestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionGrpcServer).GetQuestions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// QuestionGrpc_ServiceDesc is the grpc.ServiceDesc for QuestionGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuestionGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "questionprotoG.QuestionGrpc",
	HandlerType: (*QuestionGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuestions",
			Handler:    _QuestionGrpc_GetQuestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "questionprotoG.proto",
}
