// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: avatargrpc.proto

package protogrpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvatarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageSrc  string `protobuf:"bytes,2,opt,name=image_src,json=imageSrc,proto3" json:"image_src,omitempty"`
	Price     int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *AvatarRequest) Reset() {
	*x = AvatarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avatargrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarRequest) ProtoMessage() {}

func (x *AvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avatargrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarRequest.ProtoReflect.Descriptor instead.
func (*AvatarRequest) Descriptor() ([]byte, []int) {
	return file_avatargrpc_proto_rawDescGZIP(), []int{0}
}

func (x *AvatarRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AvatarRequest) GetImageSrc() string {
	if x != nil {
		return x.ImageSrc
	}
	return ""
}

func (x *AvatarRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AvatarRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AvatarRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AvatarsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data []*AvatarRequest `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AvatarsResponse) Reset() {
	*x = AvatarsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avatargrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarsResponse) ProtoMessage() {}

func (x *AvatarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avatargrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarsResponse.ProtoReflect.Descriptor instead.
func (*AvatarsResponse) Descriptor() ([]byte, []int) {
	return file_avatargrpc_proto_rawDescGZIP(), []int{1}
}

func (x *AvatarsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AvatarsResponse) GetData() []*AvatarRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type AvatarResponseOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data *AvatarRequest `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AvatarResponseOne) Reset() {
	*x = AvatarResponseOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avatargrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarResponseOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarResponseOne) ProtoMessage() {}

func (x *AvatarResponseOne) ProtoReflect() protoreflect.Message {
	mi := &file_avatargrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarResponseOne.ProtoReflect.Descriptor instead.
func (*AvatarResponseOne) Descriptor() ([]byte, []int) {
	return file_avatargrpc_proto_rawDescGZIP(), []int{2}
}

func (x *AvatarResponseOne) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AvatarResponseOne) GetData() *AvatarRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type EmptyAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyAvatar) Reset() {
	*x = EmptyAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avatargrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyAvatar) ProtoMessage() {}

func (x *EmptyAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_avatargrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyAvatar.ProtoReflect.Descriptor instead.
func (*EmptyAvatar) Descriptor() ([]byte, []int) {
	return file_avatargrpc_proto_rawDescGZIP(), []int{3}
}

type AvatarId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AvatarId) Reset() {
	*x = AvatarId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avatargrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarId) ProtoMessage() {}

func (x *AvatarId) ProtoReflect() protoreflect.Message {
	mi := &file_avatargrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarId.ProtoReflect.Descriptor instead.
func (*AvatarId) Descriptor() ([]byte, []int) {
	return file_avatargrpc_proto_rawDescGZIP(), []int{4}
}

func (x *AvatarId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_avatargrpc_proto protoreflect.FileDescriptor

var file_avatargrpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x0d,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x72, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x53,
	0x0a, 0x0f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x55, 0x0a, 0x11, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0d, 0x0a, 0x0b, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x1a, 0x0a, 0x08, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0xc4, 0x01, 0x0a, 0x0d, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x1a, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0e, 0x12, 0x0c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x73, 0x12,
	0x5b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x49, 0x64, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4f,
	0x6e, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x0e, 0x5a, 0x0c,
	0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_avatargrpc_proto_rawDescOnce sync.Once
	file_avatargrpc_proto_rawDescData = file_avatargrpc_proto_rawDesc
)

func file_avatargrpc_proto_rawDescGZIP() []byte {
	file_avatargrpc_proto_rawDescOnce.Do(func() {
		file_avatargrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_avatargrpc_proto_rawDescData)
	})
	return file_avatargrpc_proto_rawDescData
}

var file_avatargrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_avatargrpc_proto_goTypes = []interface{}{
	(*AvatarRequest)(nil),     // 0: protogrpc.AvatarRequest
	(*AvatarsResponse)(nil),   // 1: protogrpc.AvatarsResponse
	(*AvatarResponseOne)(nil), // 2: protogrpc.AvatarResponseOne
	(*EmptyAvatar)(nil),       // 3: protogrpc.EmptyAvatar
	(*AvatarId)(nil),          // 4: protogrpc.AvatarId
}
var file_avatargrpc_proto_depIdxs = []int32{
	0, // 0: protogrpc.AvatarsResponse.data:type_name -> protogrpc.AvatarRequest
	0, // 1: protogrpc.AvatarResponseOne.data:type_name -> protogrpc.AvatarRequest
	3, // 2: protogrpc.AvatarService.GetAvatars:input_type -> protogrpc.EmptyAvatar
	4, // 3: protogrpc.AvatarService.GetOneAvatar:input_type -> protogrpc.AvatarId
	1, // 4: protogrpc.AvatarService.GetAvatars:output_type -> protogrpc.AvatarsResponse
	2, // 5: protogrpc.AvatarService.GetOneAvatar:output_type -> protogrpc.AvatarResponseOne
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_avatargrpc_proto_init() }
func file_avatargrpc_proto_init() {
	if File_avatargrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_avatargrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avatargrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avatargrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarResponseOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avatargrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avatargrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_avatargrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avatargrpc_proto_goTypes,
		DependencyIndexes: file_avatargrpc_proto_depIdxs,
		MessageInfos:      file_avatargrpc_proto_msgTypes,
	}.Build()
	File_avatargrpc_proto = out.File
	file_avatargrpc_proto_rawDesc = nil
	file_avatargrpc_proto_goTypes = nil
	file_avatargrpc_proto_depIdxs = nil
}
