// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: questionproto.proto

package questionpbgateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuestionsGatewayClient is the client API for QuestionsGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuestionsGatewayClient interface {
	GetQuestions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuestionResponse, error)
}

type questionsGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionsGatewayClient(cc grpc.ClientConnInterface) QuestionsGatewayClient {
	return &questionsGatewayClient{cc}
}

func (c *questionsGatewayClient) GetQuestions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuestionResponse, error) {
	out := new(QuestionResponse)
	err := c.cc.Invoke(ctx, "/pb_question.QuestionsGateway/GetQuestions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionsGatewayServer is the server API for QuestionsGateway service.
// All implementations must embed UnimplementedQuestionsGatewayServer
// for forward compatibility
type QuestionsGatewayServer interface {
	GetQuestions(context.Context, *Empty) (*QuestionResponse, error)
	mustEmbedUnimplementedQuestionsGatewayServer()
}

// UnimplementedQuestionsGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedQuestionsGatewayServer struct {
}

func (UnimplementedQuestionsGatewayServer) GetQuestions(context.Context, *Empty) (*QuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuestions not implemented")
}
func (UnimplementedQuestionsGatewayServer) mustEmbedUnimplementedQuestionsGatewayServer() {}

// UnsafeQuestionsGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestionsGatewayServer will
// result in compilation errors.
type UnsafeQuestionsGatewayServer interface {
	mustEmbedUnimplementedQuestionsGatewayServer()
}

func RegisterQuestionsGatewayServer(s grpc.ServiceRegistrar, srv QuestionsGatewayServer) {
	s.RegisterService(&QuestionsGateway_ServiceDesc, srv)
}

func _QuestionsGateway_GetQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionsGatewayServer).GetQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_question.QuestionsGateway/GetQuestions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionsGatewayServer).GetQuestions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// QuestionsGateway_ServiceDesc is the grpc.ServiceDesc for QuestionsGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuestionsGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_question.QuestionsGateway",
	HandlerType: (*QuestionsGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuestions",
			Handler:    _QuestionsGateway_GetQuestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "questionproto.proto",
}
